// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSDe2Gt4xlWHUDofGbcws6PgeC2UCGeAc',
    appId: '1:556367125182:web:b1c4d6f32fdb155c9d9cef',
    messagingSenderId: '556367125182',
    projectId: 'dept-app-4306a',
    authDomain: 'dept-app-4306a.firebaseapp.com',
    storageBucket: 'dept-app-4306a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiSj6hCZeczZJNPFvnYchyUt230ho0DjI',
    appId: '1:556367125182:android:f9c4b85631e9bd059d9cef',
    messagingSenderId: '556367125182',
    projectId: 'dept-app-4306a',
    storageBucket: 'dept-app-4306a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5cJPBJYRoj9IKt8-5RkGrpKGMsDv0C68',
    appId: '1:556367125182:ios:3b88d41ec896b5e69d9cef',
    messagingSenderId: '556367125182',
    projectId: 'dept-app-4306a',
    storageBucket: 'dept-app-4306a.firebasestorage.app',
    iosBundleId: 'com.example.debtApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5cJPBJYRoj9IKt8-5RkGrpKGMsDv0C68',
    appId: '1:556367125182:ios:3b88d41ec896b5e69d9cef',
    messagingSenderId: '556367125182',
    projectId: 'dept-app-4306a',
    storageBucket: 'dept-app-4306a.firebasestorage.app',
    iosBundleId: 'com.example.debtApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSDe2Gt4xlWHUDofGbcws6PgeC2UCGeAc',
    appId: '1:556367125182:web:e7575ead8b6b46b29d9cef',
    messagingSenderId: '556367125182',
    projectId: 'dept-app-4306a',
    authDomain: 'dept-app-4306a.firebaseapp.com',
    storageBucket: 'dept-app-4306a.firebasestorage.app',
  );
}
